### ISSUE TITLE
still work ?

### ISSUE THREAD

**Issue by profesionalleet1337** [RDXLR/Forward-SMS#2]
How exactly this tool work ? I couldn't understand at all, and actually in nowdays is working or no ?
Is there any video or tutorial, so i Could see how this should be used and tested?

**Comment by Alygnt** [comment]
The tool, still works!! but in latest android errors you might get some issues. Please go through the [ReadME.md](https://github.com/Alygnt/Forward-SMS#usage) docs for the setup
