### ISSUE TITLE
I can't find IncomingSms.smali in the apk application files

### ISSUE THREAD

**Issue by Karim99z** [RDXLR/Forward-SMS#3]
I can't find IncomingSms.smali in the apk application files

**Comment by Alygnt** [comment]
Please click smali buttton on the top right corner to decode all smali files. And then try

**Comment by Karim99z** [comment]
Je ne trouve pas le bouton smali
![Screenshot_20231102-004312_APK Editor](https://github.com/Alygnt/Forward-SMS/assets/146777263/cab1288b-787c-41c1-8e94-4da64b809b23)

**Comment by Alygnt** [comment]
The APK editor you have is outdated, PLEASE DO INSTALL AND TRY THIS >> https://apkmodget.com/apps/apk-editor-pro-mod-apk-download/

**Comment by Karim99z** [comment]
Hi now I can not find the command line 0915000 there are no more than 900 lines how can we find the 0915000

**Comment by Alygnt** [comment]
I didn't mean line 0915000, It is a text... Search 0915000 as a text, you will get it...

**Comment by Karim99z** [comment]
Hello, the application is detected by Google play protect what to do to obfuscate?

**Comment by Alygnt** [comment]
Go to google play store and disable play protect

**Comment by Karim99z** [comment]
Hello I would like to learn how to obfuscate it directly without bad intention
